### ISSUE TITLE
Pause video ONLY if changed refresh rate

### ISSUE THREAD

**Issue by Obegg** [CogentRedTester/mpv-changerefresh#1]
The current script pauses the video even if the screen refresh rate wasn't changed, which is a waste of time and annoying, it makes every video in a playlist pause for 3 seconds regardless of screen refresh rate changes.
I want it to pause the video only if it did change the refresh rate.

**Comment by CogentRedTester** [comment]
Try now.

**Comment by CogentRedTester** [comment]
And man this script is so badly written, I need to just throw the whole thing out and start again from scratch. If only I had the time.

**Comment by Obegg** [comment]
> Try now.

Yes, it works, thank you!

> And man this script is so badly written, I need to just throw the whole thing out and start again from scratch. If only I had the time.

Should I open a new issue (to act as a reminder) related to rewriting the script?

**Comment by CogentRedTester** [comment]
No, I'll probably create a project board when I have the time. No guarantees though.
