### ISSUE TITLE
Make the chosen rate depend on divisibility instead of closeness.

### ISSUE THREAD

**Issue by bejelentkezni** [CogentRedTester/mpv-changerefresh#3]
Currently if you have the rates of 48 and 60, the screen will be set to 48 for videos that are 30 or 15 fps, that should really stay at 60 in those cases.

**Comment by CogentRedTester** [comment]
You can use `30-60` to set the display to 60 for 30fps videos. Should automatically apply to anything below 30 as well.

**Comment by bejelentkezni** [comment]
That doesn't really fix the problem because 24fps content would want 48Hz. And my monitor only does 48 and 60.

**Comment by CogentRedTester** [comment]
Then set 24 to 48 in the same way.

`rates=15-60,24-48,30-60,48,60`
