### ISSUE TITLE
I am unable to change the keybindings

### ISSUE THREAD

**Issue by user18081972** [CogentRedTester/mpv-changerefresh#8]
All other features of the plugin work great for me, no problems. Except for the rebinding of keys.

I have tried changing the keybindings to revert-refresh, by editing input.conf.
this is my full input.conf:
```
i         match-refresh
Ctrl+i    revert-refresh
```

but it is not responding to my keybindings, however the default f10 and ctrl+f10 are still working with said input.conf set to i and ctrl+i.
if i add for example "i             cycle fullscreen" that works just fine, so the input.conf is being applied. can you try if it actually works for you, and help me find the cause?

mpv [v0.35.1]
mpv-changerefresh current version

**Comment by CogentRedTester** [comment]
Try:

```
i         script-binding match-refresh
Ctrl+i    script-binding revert-refresh
```

**Comment by user18081972** [comment]
That totally works, thank you!

I used
```
i         match-refresh
Ctrl+i    revert-refresh
```
before, because thats what it said in readme.md, never had to use script-binding before.

I will close the issue because I see no further issue.
